### ISSUE TITLE
查看了你的代码， 请问读取 __consumer_offsets 这个topic 读取不会影响kafka吗

### ISSUE THREAD

**Issue by 55utah** [kairosdb/kafka-monitor#1]
很多书都说尽量不要读取这个topic

**Comment by brianhks** [comment]
>> Check out your code, will read __consumer_offsets this topic read will not affect kafka?

If that translation is correct - this doesn't adversely effect Kafka in any way.  We are running this against an 80 node Kafka cluster with over 100 topics without problems.

**Comment by 55utah** [comment]
> > > Check out your code, will read __consumer_offsets this topic read will not affect kafka?
> 
> If that translation is correct - this doesn't adversely effect Kafka in any way. We are running this against an 80 node Kafka cluster with over 100 topics without problems.

thx , translation basicly is correct.
